global:
  imageTag: latest

frontend:
  replicas: 2
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/frontend
  containerPort: 80
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

auth:
  replicas: 1
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/auth-service
  containerPort: 5000
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

account:
  replicas: 1
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/account-service
  containerPort: 5001
  service:
    type: ClusterIP
    port: 5001
    targetPort: 5001

transaction:
  replicas: 1
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/transaction-service
  containerPort: 5002
  service:
    type: ClusterIP
    port: 5002
    targetPort: 5002

ingress:
  enabled: true
  host: cdboi.local
  scheme: internet-facing
