global:
  imageTag: latest

frontend:
  replicas: 2
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/frontend
  service:
    type: LoadBalancer
    port: 80
    targetPort: 80

auth:
  replicas: 1
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/auth-service
  service:
    type: ClusterIP
    port: 5000

account:
  replicas: 1
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/account-service
  service:
    type: ClusterIP
    port: 5001

transaction:
  replicas: 1
  image:
    repository: 096803082838.dkr.ecr.ap-south-1.amazonaws.com/transaction-service
  service:
    type: ClusterIP
    port: 5002
