apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: {{ .Values.account.replicas }}
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: {{ .Values.account.image.repository }}:{{ .Values.global.imageTag }}
          ports:
            - containerPort: {{ .Values.account.containerPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.account.livenessProbe.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.account.readinessProbe.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
