apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  type: {{ .Values.account.service.type }}
  selector:
    app: account-service
  ports:
    - port: {{ .Values.account.service.port }}
      targetPort: {{ .Values.account.service.targetPort }}
