apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  type: {{ .Values.transaction.service.type }}
  selector:
    app: transaction-service
  ports:
    - port: {{ .Values.transaction.service.port }}
      targetPort: {{ .Values.transaction.service.targetPort }}
