apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction
  ports:
    - port: {{ .Values.transaction.port }}
      targetPort: {{ .Values.transaction.port }}
