apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  labels:
    app: transaction-service
spec:
  replicas: {{ .Values.transaction.replicas }}
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: {{ .Values.transaction.image.repository }}:{{ .Values.global.imageTag }}
          ports:
            - containerPort: {{ .Values.transaction.containerPort }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.transaction.containerPort }}
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.transaction.containerPort }}
